# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Younique' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'NewRelicAgent', '5.12.3'
  
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
  pod 'MBProgressHUD'

  target 'YouniqueTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YouniqueUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
